### ISSUE TITLE
Envio de RPS pelo site informa que esta fora do formato

### ISSUE THREAD

**Issue by danielcembranelli** [nfephp-org/sped-nfse-ginfes#3]
boa noite, 

baixei o projeto de vocês, porem ao enviar pelo site do Ginfes diz que esta fora da estrutura.

Sabem o que pode ser?

[]s

**Comment by marciotisouza** [comment]
Bom dia, desculpe a demora pois não recebi a notificação da sua pergunta.

Ainda estamos mexendo com este layout, neste mês de setembro/2019 irei posta uma atualização com o processo completo.

**Comment by marciotisouza** [comment]
Bom dia, fiz a atualização do projeto, se puder fazer os testes e dar um retorno !

**Comment by lipefit** [comment]
Boa noite. Fiz alguns testes e obtive o mesmo problema do Daniel.
Acredito então que mesmo com a atualização o problema persiste.

**Comment by lipefit** [comment]
Boa noite. Conseguiram ver esse ponto? 
Em caso negativo, vou tentar alterar o código pra que o formato fique correto.

**Comment by marciotisouza** [comment]
Bom dia, estou concluindo os ajustes na classe e vou postar as melhorias na semana que vem, caso tenha notado algum problema pode me passar.

**Comment by lipefit** [comment]
Por hora nenhum outro problema. Só essa questão de estar fora do formato.

**Comment by marciotisouza** [comment]
Olá, Lipefit

     Em qual cidade você tentando postar o arquivo, se puder passar o site para eu ver.

**Comment by lipefit** [comment]
Estou tentando em Guarulhos.
Quando tento enviar pela aplicação, recebo a mensagem: 

> Call to undefined function NFePHP\NFSeGinfes\Common\Soap\Vazio()

Quando tento enviar o xml gerado direto pelo site do ginfes, recebo a mensagem de que está fora do formato.

**Comment by lipefit** [comment]
Olá, alguma atualização?
