### ISSUE TITLE
Faltando diretório Vendor

### ISSUE THREAD

**Issue by lipefit** [nfephp-org/sped-nfse-ginfes#5]
Boa tarde, tudo bem?
O diretório vendor está faltando no projeto?
O bootstrap.php chama o autoload, que deveria estar nesse diretório.
Percebi também que o mesmo está para ser ignorado pelo git.

Realmente está faltando, ou eu estou fazendo algo de errado? Gostaria de testar o projeto, e quem sabe tentar contribuir de alguma forma, pois é algo muito útil.

**Comment by robmachado** [comment]
@lipefit 
A pasta vendor é criada ao usar o composer.
**Mas entenda, o arquivo bootstrap é usado apenas e SOMENTE para os testes e exemplos, na sua aplicação você NUNCA vai usar o arquivo bootstrap.php de nenhum dos projetos do nfephp-org.**

Quando estamos fazendo desenvolvimento e testes, o projeto é testado **SOZINHO**, com dados manuais ele não faz parte de nenhum aplicativo e portanto necessita de uma pasta vendor própria.
Mas quando é usado em um aplicativo, o próprio aplicativo é que terá a pasta vendor e o autoload.php na sua pasta raiz.

**Comment by robmachado** [comment]
https://www.youtube.com/watch?v=gXQZlrbzesc

**Comment by lipefit** [comment]
Sim, imaginei isso.
De qualquer forma, ao tentar instalar via composer, é retornado um erro de InvalidArgumentException.

**Comment by robmachado** [comment]
Meu amigo não dá para saber o que você está fazendo, nem saber onde ou como ocorre esse exception

**Comment by lipefit** [comment]
O exception acontece ao tentar instalar o projeto via composer.
Para isso estou utilizando: "composer require nfephp-org/sped-nfse-ginfes"
Como ainda não tem a instrução de instalação no README, imaginei que seria assim, de acordo com o nome do projeto no composer.json, mas acredito que não, pois a exception é justamente por não encontrar o pacote.

**Comment by lipefit** [comment]
Boa noite. O problema acima foi resolvido, consegui fazer a instalação.
Mas ao enviar para o ginfes, recebo uma mensagem dizendo que o arquivo enviadoestá fora da estrutura do arquivo xml de entrada.

**Comment by lipefit** [comment]
Boa noite. O problema acima foi resolvido, consegui fazer a instalação.
Mas ao enviar para o ginfes, recebo uma mensagem dizendo que o arquivo enviado está fora da estrutura do arquivo xml de entrada. Como já tem uma issue aberta sobre isso, farei a interação por lá.
